version: '1'
services:
  eurekaserver:
    image: eureka-server/eureka-server
    container_name: eureka-server
    ports:
      - '8761:8761'
  configserver:
    image: config-server
    container_name: config-server
    environment:
      - EUREKA_SERVER_ADDRESS=http://eurekaserver:8761/eureka
    depends_on:
      - eurekaserver
    ports:
      - '9296:9296'
    healthcheck:
      test: ["CMD","curl","-f","http://configserver:9296/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 3
  apigateway:
    image: 'apigateway'
    container_name: 'apigateway'
    environment:
      - EUREKA_SERVER_ADDRESS=http://eurekaserver:8761/eureka
      - CONFIG_SERVER_URL=http://configserver:9296/
      - PRODUCT_LINK=productservice
      - ORDER_LINK=orderservices
    depends_on:
       configserver:
         condition: service_healthy
    ports:
      - '9191:9191'
  databaseserver:
    image: 'postgres'
    container_name: 'posgresqldatabase'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ecommerce
    ports:
      - '5432:5432'
#   volumes:
#      - /var/lib/postgresql/data:C:/postgrescontainer
  productservice:
    image: 'productservice'
    container_name: 'productservice'
    environment:
      - CONFIG_SERVER_URL=http://configserver:9296/
      - EUREKA_SERVER_ADDRESS=http://eurekaserver:8761/eureka
      - DB_HOST=databaseserver
    ports:
      - '8082:8082'
    depends_on:
      configserver:
        condition: service_healthy

  orderservices:
    image: 'orderservices'
    container_name: 'orderservices'
    environment:
      - CONFIG_SERVER_URL=http://configserver:9296/
      - EUREKA_SERVER_ADDRESS=http://eurekaserver:8761/eureka
      - DB_HOST=databaseserver
    ports:
      - '8081:8081'
    depends_on:
      configserver:
        condition: service_healthy

