server:
  port: 8761

spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: "${HOSTNAME:localhost}.eureka"
  client:
    register-with-eureka: false
    fetch-registry: false
