server:
  port: 8081

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/ecommerce
    username: postgres
    password: root
  application:
    name: Order-Service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

