server:
  port: 8081

spring:
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:5432/ecommerce
    username: postgres
    password: root
  application:
    name: Order-Service
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:9296}


#
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    hostname: localhost

