server:
  port: 9191

spring:
  application:
    name: ecommerce-apigateway
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: http://localhost:8081
          predicates:
            - Path=/order/**

        - id: product-service
          uri: http://localhost:8082
          predicates:
            - Path=/product/**


management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost